const array = [
  {
    "title": "Dangal",
    "Year": 2016,
    "Genre": "Biography, Drama, Sport",
    "Actors": "Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh, Sanya Malhotra",
    "Plot": "Former wrestler Mahavir Singh Phogat trains his daughters Geeta and Babita to become India's first world-class female wrestlers against all odds.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "Nominated for 1 Oscar. Another 44 wins & 4 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr7V-J-SLeOYyxy7Zs4ruENBnQatpmfxBjDA&usqp=CAU",
    "imdbRating": 8.4,
    "imdbVotes": "161,088",
    "imdbID": "tt5074352",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x4y9tvh"
  },
  {
    "title": "Black Mirror",
    "Year": 2011,
    "Genre": "Drama, Sci-Fi, Thriller",
    "Actors": "Daniel Lapaine, Hannah John-Kamen, Michaela Coel, Beatrice Robertson-Jones",
    "Plot": "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
    "Language": "English",
    "Country": "UK, USA",
    "Awards": "Won 8 Primetime Emmys. Another 30 wins & 68 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsHmHfAUmzfww0XdQaxim6cD95Fj1lLFthfg&usqp=CAU",
    "imdbRating": 8.8,
    "imdbVotes": "456,628",
    "imdbID": "tt2085059",
    "Type": "series",
    "VideoLink":"https://www.dailymotion.com/embed/video/x8le9qp"
  },
  {
    "title": "PK",
    "Year": 2014,
    "Genre": "Comedy, Drama, Fantasy",
    "Actors": "Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman Irani",
    "Plot": "An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to evaluate the impact of religion on its people.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "12 wins & 21 nominations.",
    "Poster": "https://upload.wikimedia.org/wikipedia/en/c/c3/PK_poster.jpg",
    "imdbRating": 8.1,
    "imdbVotes": "160,618",
    "imdbID": "tt2338151",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x2c25dr"
  },
  {
    "title": "Mirzapur",
    "Year": 2018,
    "Genre": "Action, Crime, Drama",
    "Actors": "Pankaj Tripathi, Ali Fazal, Divyendu Sharma, Shweta Tripathi",
    "Plot": "A shocking incident at a wedding procession ignites a series of events entangling the lives of two families in the lawless city of Mirzapur.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "5 wins & 5 nominations.",
    "Poster": "https://m.media-amazon.com/images/I/716krwewimL._AC_UF1000,1000_QL80_.jpg",
    "imdbRating": 8.4,
    "imdbVotes": "59,101",
    "imdbID": "tt6473300",
    "Type": "series",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x8o1krh"
  },
  {
    "title": "Andhadhun",
    "Year": 2018,
    "Genre": "Crime, Thriller",
    "Actors": "Ayushmann Khurrana, Tabu, Radhika Apte, Anil Dhawan",
    "Plot": "A series of mysterious events take place in the life of a blind pianist who becomes the prime witness of multiple murders.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "19 wins & 15 nominations.",
    "Poster": "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2018/09/fgg-1536050018.jpg",
    "imdbRating": 8.3,
    "imdbVotes": "69,442",
    "imdbID": "tt8108198",
    "Type": "movie",
     "VideoLink":"https://www.dailymotion.com/embed/video/x6t0exy"
  },
  {
    "title": "3 Idiots",
    "Year": 2009,
    "Genre": "Comedy, Drama",
    "Actors": "Aamir Khan, Madhavan, Sharman Joshi, Kareena Kapoor",
    "Plot": "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them 'idiots.'",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "25 wins & 11 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ71rMVF7wGupHuBu3HlZwR4V6l7gYreoAIkQ&usqp=CAU",
    "imdbRating": 8.4,
    "imdbVotes": "356,348",
    "imdbID": "tt1187043",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x4k2bdw"
  },
  {
    "title": "The Family Man",
    "Year": 2019,
    "Genre": "Action, Comedy, Drama",
    "Actors": "Manoj Bajpayee, Sharib Hashmi, Priyamani, Gul Panag",
    "Plot": "A working man from the National Investigation Agency tries to protect the nation from terrorism while also balancing his family life.",
    "Language": "Hindi, Tamil, Telugu",
    "Country": "India",
    "Awards": "2 wins & 1 nomination.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSMa6-ydLcgucx-hv2mG24rHE6TdtWMQpwlFq95FcYXUNPNracr-jiiLaq_kRNeQ-L-sY&usqp=CAU",
    "imdbRating": 8.5,
    "imdbVotes": "29,898",
    "imdbID": "tt9544034",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8hr0l0"
  },
  {
    "title": "Breathe",
    "Year": 2018,
    "Genre": "Drama, Thriller",
    "Actors": "Madhavan, Amit Sadh, Sapna Pabbi, Shriswara",
    "Plot": "A series about a man who is willing to go to the greatest lengths to save his dying son.",
    "Language": "Hindi, English, Marathi, Tamil, Telugu, Kannada",
    "Country": "India",
    "Awards": "1 nomination.",
    "Poster":"https://i.pinimg.com/736x/22/27/96/2227961c6a519e6784968a3430f85620.jpg",
    "imdbRating": 8.4,
    "imdbVotes": "8,896",
    "imdbID": "tt6469428",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8hsh4g"
  },
  {
    "title": "Lagaan: Once Upon a Time in India",
    "Year": 2001,
    "Genre": "Adventure, Drama, Musical",
    "Actors": "Aamir Khan, Gracy Singh, Rachel Shelley, Paul Blackthorne",
    "Plot": "The people of a small village in Victorian India stake their future on a game of cricket against their ruthless British rulers.",
    "Language": "Hindi, English, Awadhi",
    "Country": "India",
    "Awards": "Nominated for 1 Oscar. Another 44 wins & 20 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ4C4cVoS_ErvQHrVt4jWPjl2BzYiELsEaOVGlgv3uNso4j7e4lZ_ayFotj0QsU_h5z7w&usqp=CAU",
    "imdbRating": 8.1,
    "imdbVotes": "110,865",
    "imdbID": "tt0169102",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x8lgq0d"
  },
  {
    "title": "Queen",
    "Year": 2013,
    "Genre": "Adventure, Comedy, Drama",
    "Actors": "Kangana Ranaut, Rajkummar Rao, Lisa Haydon, Jeffrey Ho",
    "Plot": "A Delhi girl from a traditional family sets out on a solo honeymoon after her marriage gets canceled.",
    "Language": "Hindi, English, French, Dutch",
    "Country": "India",
    "Awards": "31 wins & 6 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_-6lTFpvjQU7jumgwvVA35bTqX1fHJ1nV2g&usqp=CAU",
    "imdbRating": 8.1,
    "imdbVotes": "53,257",
    "imdbID": "tt3322420",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x2e9zew"
  },
  {
    "title": "Barfi!",
    "Year": 2012,
    "Genre": "Adventure, Comedy, Drama",
    "Actors": "Ranbir Kapoor, Priyanka Chopra, Ileana D'Cruz, Saurabh Shukla",
    "Plot": "Three young people learn that love can neither be defined nor contained by society's norms of normal and abnormal.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "19 wins & 37 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN88yqYet91-G-B5neJHqlzA2Po7eWAUJA7tPh9gNAvePnTZzPs5NT7yEC8Mkh4vOawwU&usqp=CAU",
    "imdbRating": 8.1,
    "imdbVotes": "58,564",
    "imdbID": "tt2082197",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x3ug3uf"
  },
  {
    "title": "Kabhi Khushi Kabhie Gham...",
    "Year": 2001,
    "Genre": "Drama, Musical, Romance",
    "Actors": "Shah Rukh Khan, Kajol, Amitabh Bachchan, Hrithik Roshan",
    "Plot": "Yashvardhan Raichand lives a very wealthy lifestyle along with his wife, Nandini, and two sons, Rahul and Rohan.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "15 wins & 25 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmZOI2hqGkjMM6ZqqFE2JrolR0SvnGq600xA&usqp=CAU",
    "imdbRating": 7.4,
    "imdbVotes": "43,707",
    "imdbID": "tt0248126",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/xo25ir"
  },

  {
    "title": "Made in Heaven",
    "Year": 2019,
    "Genre": "Drama, Romance",
    "Actors": "Arjun Mathur, Sobhita Dhulipala, Jim Sarbh, Kalki Koechlin",
    "Plot": "It is the story of two wedding planners in Delhi, where tradition jostles with modern aspirations against the backdrop of big fat Indian weddings revealing many secrets and lies.",
    "Language": "Hindi, English",
    "Country": "India",
    "Awards": "Nominated for 1 International Emmy. Another 4 wins & 8 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9xG7MPh8j92yBuLlynQyjW-QBjRz8-k88Tz8PTQ02cW-yD5PeVfr8fwUWYXbPcnx95rA&usqp=CAU",
    "imdbRating": 8.3,
    "imdbVotes": "10,988",
    "imdbID": "tt9495224",
    "Type": "series",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x81l0vg"
  },
  {
    "title": "Gully Boy",
    "Year": 2019,
    "Genre": "Drama, Music",
    "Actors": "Ranveer Singh, Alia Bhatt, Siddhant Chaturvedi, Vijay Raaz",
    "Plot": "A coming-of-age story based on the lives of street rappers in Mumbai.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "Nominated for 1 Oscar. Another 59 wins & 75 nominations.",
    "Poster": "https://m.media-amazon.com/images/S/pv-target-images/6837cb65d1dc471e1524c795465dd3ed340e82c8a19d5a6dac07c3228dd9b447.jpg",
    "imdbRating": 8.1,
    "imdbVotes": "52,631",
    "imdbID": "tt2395469",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x8hqlwe"
  },
  {
    "title": "Sacred Games",
    "Year": 2018,
    "Genre": "Action, Crime, Drama",
    "Actors": "Saif Ali Khan, Nawazuddin Siddiqui, Radhika Apte, Neeraj Kabi",
    "Plot": "A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "Nominated for 1 Primetime Emmy. Another 8 wins & 13 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM37d8Do5Qakv_iI2jOV1nhrAwR2Uvl-VXduaGN8tZoJOK4XGAZxkWtgzC_UDdQx29hzg&usqp=CAU",
    "imdbRating": 8.6,
    "imdbVotes": "64,753",
    "imdbID": "tt6077448",
    "Type": "series",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x6mw07m"
  },
  {
    "title": "Delhi Crime",
    "Year": 2019,
    "Genre": "Crime, Drama, Thriller",
    "Actors": "Shefali Shah, Rajesh Tailang, Rasika Dugal, Anurag Arora",
    "Plot": "Based on the Nirbhaya case, Delhi Crime follows the aftermath of the gang rape of a young woman on a bus in Delhi, focusing on the efforts of the Delhi Police to bring the perpetrators to justice.",
    "Language": "Hindi, English",
    "Country": "India",
    "Awards": "Won 7 Primetime Emmys. Another 3 wins & 5 nominations.",
    "Poster": "https://economictimes.indiatimes.com/thumb/msid-93917039,width-1200,height-900,resizemode-4,imgsize-63478/delhi-crime.jpg?from=mdr",
    "imdbRating": 8.5,
    "imdbVotes": "30,828",
    "imdbID": "tt9398466",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x74lpct"
  },

  {
    "title": "Criminal Justice",
    "Year": 2019,
    "Genre": "Crime, Drama, Mystery",
    "Actors": "Vikrant Massey, Pankaj Tripathi, Rucha Inamdar, Jackie Shroff",
    "Plot": "Sex, drugs, and a gruesome murder. An edgy one night stand turns into a nightmare for Aditya, when he wakes up with blood on his hands.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "1 win & 1 nomination.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BZmVjMDAzZjMtNGNiNS00NzY3LTk2YjUtYjg0ZWVhYzU3N2ZlXkEyXkFqcGdeQXVyMTE3MzIyMDM5._V1_.jpg",
    "imdbRating": 8.1,
    "imdbVotes": "4,852",
    "imdbID": "tt8688506",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8hr69g"
  },


  {
    "title": "Paatal Lok",
    "Year": 2020,
    "Genre": "Crime, Drama, Thriller",
    "Actors": "Jaideep Ahlawat, Neeraj Kabi, Abhishek Banerjee, Gul Panag",
    "Plot": "A down and out cop lands the case of a lifetime when four suspects are nabbed in the assassination attempt of a prime-time journalist.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "1 win & 3 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTE5NWUyMmYtMWE1My00ZDhiLWExZjEtMGJjYTA0OGYwZjIwXkEyXkFqcGdeQXVyODQ5NDUwMDk@._V1_FMjpg_UX1000_.jpg",
    "imdbRating": 7.9,
    "imdbVotes": "19,738",
    "imdbID": "tt9680440",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x7u1u9m"
  },
  {
    "title": "Asur: Welcome to Your Dark Side",
    "Year": 2020,
    "Genre": "Crime, Drama, Thriller",
    "Actors": "Arshad Warsi, Barun Sobti, Anupriya Goenka, Sharib Hashmi",
    "Plot": "A unique crime thriller that pits two opposing worlds against each other. The less explored, intricate world of forensic science and the deep mysticism of ancient Indian Mythology.",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "Nominated for 1 Indian Television Academy Award.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYzNiYTkyZjgtODRmNC00ZTc0LWIzZDgtODYyZWIwMTNhZjhiXkEyXkFqcGdeQXVyMTE0MzY0NjE1._V1_.jpg",
    "imdbRating": 8.4,
    "imdbVotes": "9,456",
    "imdbID": "tt10155688",
    "Type": "series",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x8ht6kw"
  },
  {
    "title": "Masaan",
    "Year": 2015,
    "Genre": "Drama",
    "Actors": "Richa Chadha, Sanjay Mishra, Vicky Kaushal, Pankaj Tripathi",
    "Plot": "Four lives intersect along the Ganges: a low-caste boy in hopeless love, a daughter ridden with guilt of a sexual encounter ending in a tragedy, a hapless father with fading morality, and a spirited child yearning for a family, long to escape the moral constructs of a small-town.",
    "Language": "Hindi",
    "Country": "India, France",
    "Awards": "15 wins & 21 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BY2Q1ZDQ3NTYtMTU5NS00NjA3LTkzMzEtM2M5NjU0ZTFmZTNjXkEyXkFqcGdeQXVyODMyODMxNDY@._V1_.jpg",
    "imdbRating": 8.1,
    "imdbVotes": "22,522",
    "imdbID": "tt4635372",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x2t2a4d"
  },

  {
    "title": "Avatar",
    "Year": 2009,
    "Genre": "Action, Adventure, Fantasy",
    "Actors": "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
    "Plot": "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    "Language": "English, Spanish",
    "Country": "USA, UK",
    "Awards": "Won 3 Oscars. Another 80 wins & 121 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
    "imdbRating": 7.9,
    "imdbVotes": "890,617",
    "imdbID": "tt0499549",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x8d7o52"
  },
  {
    "title": "I Am Legend",
    "Year": 2007,
    "Genre": "Drama, Horror, Sci-Fi",
    "Actors": "Will Smith, Alice Braga, Charlie Tahan, Salli Richardson-Whitfield",
    "Plot": "Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.",
    "Language": "English",
    "Country": "USA",
    "Awards": "9 wins & 21 nominations.",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWJdy99kNusMs3-oeN4mFQFj0oVANkjzpG-Q&usqp=CAU",
    "imdbRating": 7.2,
    "imdbVotes": "533,874",
    "imdbID": "tt0480249",
    "Type": "movie", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8hjus8"
  },
  {
    "title": "Aarya",
    "Year": 2020,
    "Genre": "Action, Crime, Drama",
    "Actors": "Sushmita Sen, Vikas Kumar, Namit Das, Sikandar Kher",
    "Plot": "When her world suddenly turns upside down, will Aarya become the very thing she hated? How far will she go to survive and protect her family?",
    "Language": "Hindi",
    "Country": "India",
    "Awards": "1 win & 6 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNzY1NDE2MWQtNzJlOC00MGZiLTkxN2YtMTQ5YWVkMTA2MGU5XkEyXkFqcGdeQXVyMTE0MDk1NjA1._V1_.jpg",
    "imdbRating": 7.9,
    "imdbVotes": "8,683",
    "imdbID": "tt10366206",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8seqhk"
  },
  {
    "title": "300",
    "Year": 2006,
    "Genre": "Action, Drama, Fantasy",
    "Actors": "Gerard Butler, Lena Headey, Dominic West, David Wenham",
    "Plot": "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.",
    "Language": "English",
    "Country": "USA",
    "Awards": "16 wins & 42 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMjAzNTkzNjcxNl5BMl5BanBnXkFtZTYwNDA4NjE3._V1_SX300.jpg",
    "imdbRating": 7.7,
    "imdbVotes": "611,046",
    "imdbID": "tt0416449",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x29sdv"
  },
  {
    "title": "The Avengers",
    "Year": 2012,
    "Genre": "Action, Sci-Fi, Thriller",
    "Actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    "Plot": "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
    "Language": "English, Russian",
    "Country": "USA",
    "Awards": "Nominated for 1 Oscar. Another 34 wins & 75 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg",
    "imdbRating": 8.1,
    "imdbVotes": "1,003,301",
    "imdbID": "tt0848228",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/xp4uha"
  },
  {
    "title": "The Wolf of Wall Street",
    "Year": 2013,
    "Genre": "Biography, Comedy, Crime",
    "Actors": "Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey",
    "Plot": "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    "Language": "English, French",
    "Country": "USA",
    "Awards": "Nominated for 5 Oscars. Another 35 wins & 154 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
    "imdbRating": 8.2,
    "imdbVotes": "786,985",
    "imdbID": "tt0993846",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x16lmhh"
  },
  {
    "title": "Interstellar",
    "Year": 2014,
    "Genre": "Adventure, Drama, Sci-Fi",
    "Actors": "Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow",
    "Plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "Language": "English",
    "Country": "USA, UK",
    "Awards": "Won 1 Oscar. Another 39 wins & 134 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg",
    "imdbRating": 8.6,
    "imdbVotes": "937,412",
    "imdbID": "tt0816692",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x27421u"
  },
  {
    "title": "Game of Thrones",
    "Year": 2011,
    "Genre": "Adventure, Drama, Fantasy",
    "Actors": "Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington",
    "Plot": "While a civil war brews between several noble families in Westeros, the children of the former rulers of the land attempt to rise up to power. Meanwhile a forgotten race, bent on destruction, plans to return after thousands of years in the North.",
    "Language": "English",
    "Country": "USA, UK",
    "Awards": "Won 1 Golden Globe. Another 185 wins & 334 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMjM5OTQ1MTY5Nl5BMl5BanBnXkFtZTgwMjM3NzMxODE@._V1_SX300.jpg",
    "imdbRating": 9.5,
    "imdbVotes": "1,046,830",
    "imdbID": "tt0944947",
    "Type": "series",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x26mmdf"
  },
  {
    "title": "Vikings",
    "Year": 2013,
    "Genre": "Action, Drama, History",
    "Actors": "Travis Fimmel, Clive Standen, Gustaf Skarsgård, Katheryn Winnick",
    "Plot": "The world of the Vikings is brought to life through the journey of Ragnar Lothbrok, the first Viking to emerge from Norse legend and onto the pages of history - a man on the edge of myth.",
    "Language": "English, Old English, Norse, Old, Latin",
    "Country": "Ireland, Canada",
    "Awards": "Nominated for 7 Primetime Emmys. Another 17 wins & 49 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BOTEzNzI3MDc0N15BMl5BanBnXkFtZTgwMzk1MzA5NzE@._V1_SX300.jpg",
    "imdbRating": 8.6,
    "imdbVotes": "198,041",
    "imdbID": "tt2306299",
    "Type": "series",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x8a0wwy"
  },
  {
    "title": "Gotham",
    "Year": 2014,
    "Genre": "Action, Crime, Drama",
    "Actors": "Ben McKenzie, Donal Logue, David Mazouz, Sean Pertwee",
    "Plot": "The story behind Detective James Gordon's rise to prominence in Gotham City in the years before Batman's arrival.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Nominated for 4 Primetime Emmys. Another 3 wins & 22 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMTY2MjMwNDE4OV5BMl5BanBnXkFtZTgwNjI1NjU0OTE@._V1_SX300.jpg",
    "imdbRating": 8.0,
    "imdbVotes": "133,375",
    "imdbID": "tt3749900",
    "Type": "series",
    "VideoLink":"https://www.dailymotion.com/embed/video/x1taktl"
  },
  {
    "title": "Power",
    "Year": 2014,
    "Genre": "Crime, Drama",
    "Actors": "Omari Hardwick, Joseph Sikora, Andy Bean, Lela Loren",
    "Plot": "James \"Ghost\" St. Patrick, a wealthy New York night club owner who has it all, catering for the city's elite and dreaming big, lives a double life as a drug kingpin.",
    "Language": "English",
    "Country": "USA",
    "Awards": "1 win & 6 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BOTA4NTkzMjUzOF5BMl5BanBnXkFtZTgwNzg5ODkxOTE@._V1_SX300.jpg",
    "imdbRating": 8.0,
    "imdbVotes": "14,770",
    "imdbID": "tt3281796",
    "Type": "series",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x7cpz1n"
  },
  {
    "title": "Breaking Bad",
    "Year": 2008,
    "Genre": "Crime, Drama, Thriller",
    "Actors": "Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris",
    "Plot": "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's financial future.",
    "Language": "English, Spanish",
    "Country": "USA",
    "Awards": "Won 2 Golden Globes. Another 132 wins & 218 nominations.",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMTQ0ODYzODc0OV5BMl5BanBnXkFtZTgwMDk3OTcyMDE@._V1_SX300.jpg",
    "imdbRating": 9.5,
    "imdbVotes": "889,883",
    "imdbID": "tt0903747",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x86esfl"
  },
  {

    "title": "Doctor Strange",
    "Year": 2016,
    "Genre": "Action, Adventure, Fantasy",
    "Actors": "Rachel McAdams, Benedict Cumberbatch, Mads Mikkelsen, Tilda Swinton",
    "Plot": "After his career is destroyed, a brilliant but arrogant and conceited surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg",
    "imdbRating": 7.5,
    "imdbVotes": "889,7598",
    "imdbID": "tt1211837",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x45jn9c"
  },
  {
    "title": "Rogue One: A Star Wars Story",
    "Year": 2016,
    "Genre": "Action, Adventure, Sci-Fi",
    "Actors": "Felicity Jones, Riz Ahmed, Mads Mikkelsen, Ben Mendelsohn",
    "Plot": "The Rebellion makes a risky move to steal the plans to the Death Star, setting up the epic saga to follow.",
    "Language": "English",
    "Country": "USA",
    "Awards": "1 nomination.",
    "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQyMzI2OTA3OF5BMl5BanBnXkFtZTgwNDg5NjQ0OTE@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
    "imdbRating": 6.5,
    "imdbVotes": "N/A",
    "imdbID": "tt3748528",
    "Type": "movie",    
    "VideoLink":"https://www.dailymotion.com/embed/video/x8tmjro"
  },
  {

    "title": "Assassin's Creed",
    "Year": 2016,
    "Genre": "Action, Adventure, Fantasy",
    "Actors": "Michael Fassbender, Michael Kenneth Williams, Marion Cotillard, Jeremy Irons",
    "Plot": "When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.",
    "Language": "English",
    "Country": "UK, France, USA, Hong Kong",
    "Awards": "N/A",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMTU2MTQwMjU1OF5BMl5BanBnXkFtZTgwMDA5NjU5ODE@._V1_SX300.jpg",
    "imdbRating": 5.6,
    "imdbVotes": "N/A",
    "imdbID": "tt2094766",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x8fjhub"
  },
  {

    "title": "Luke Cage",
    "Year": 2016,
    "Genre": "Action, Crime, Drama",
    "Actors": "Mahershala Ali, Mike Colter, Frankie Faison, Erik LaRay Harvey",
    "Plot": "Given superstrength and durability by a sabotaged experiment, a wrongly accused man escapes prison to become a superhero for hire.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://ia.media-imdb.com/images/M/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_SX300.jpg",
    "imdbRating": 7.2,
    "imdbVotes": "N/A",
    "imdbID": "tt3322314",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x4nxz3q"
  },

  {
    "title": "They Shall Not Grow Old",
    "Year": 2018,
    "Genre": "Documentary, History, War",
    "Actors": "Mark Kermode, Peter Jackson",
    "Plot": "A documentary about World War I with never-before-seen footage to commemorate the centennial of the end of the war.",
    "Language": "English",
    "Country": "UK, New Zealand",
    "Awards": "Nominated for 1 BAFTA Film Award. Another 4 wins & 10 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZThmYzUtNDJhOC00ZWY4LThiNmMtZDgxNjE3Yzk4NDU1XkEyXkFqcGdeQXVyNTk5Nzg1NjQ@._V1_SX300.jpg",
    "imdbRating": 8.3,
    "imdbVotes": "21,722",
    "imdbID": "tt7905466",
    "Type": "movie", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x6xopwj"
  },
  {
    "title": "Midnight Family",
    "Year": 2019,
    "Genre": "Documentary, Action, Crime, Drama",
    "Actors": "Fer Ochoa, Josue Ochoa, Juan Ochoa",
    "Plot": "In Mexico City's wealthiest neighborhoods, the Ochoa family runs a private ambulance, competing with other for-profit EMTs for patients in need of urgent help.",
    "Language": "Spanish",
    "Country": "Mexico",
    "Awards": "24 wins & 20 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMGYyZTk5MjYtNGY2ZS00NzRhLTgwMWMtZjhmMmQ4OGFkNTNiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "imdbRating": 7.7,
    "imdbVotes": 330,
    "imdbID": "tt6010976",
    "Type": "movie", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x7nqym2"
  },
  {
    "title": "Pain & Gain",
    "Year": 2013,
    "Genre": "Action, Comedy, Crime, Drama",
    "Actors": "Mark Wahlberg, Dwayne Johnson, Anthony Mackie, Tony Shalhoub",
    "Plot": "A trio of bodybuilders in Florida get caught up in an extortion ring and a kidnapping scheme that goes terribly wrong.",
    "Language": "English",
    "Country": "USA",
    "Awards": "4 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTU0NDE5NTU0OV5BMl5BanBnXkFtZTcwMzI1OTMzOQ@@._V1_SX300.jpg",
    "imdbRating": 6.4,
    "imdbVotes": "191,388",
    "imdbID": "tt1980209",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x28dhej"
  },
  {
    "title": "The Irishman",
    "Year": 2019,
    "Genre": "Biography, Crime, Drama",
    "Actors": "Robert De Niro, Al Pacino, Joe Pesci, Harvey Keitel",
    "Plot": "A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.",
    "Language": "English, Italian, Latin, Spanish",
    "Country": "USA",
    "Awards": "Nominated for 5 Golden Globes. Another 35 wins & 159 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMGUyM2ZiZmUtMWY0OC00NTQ4LThkOGUtNjY2NjkzMDJiMWMwXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg",
    "imdbRating": 8.2,
    "imdbVotes": "144,536",
    "imdbID": "tt1302006",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x7eu20b"
  },
  {
    "title": "Once Upon a Time... in Hollywood",
    "Year": 2019,
    "Genre": "Comedy, Drama",
    "Actors": "Leonardo DiCaprio, Brad Pitt, Margot Robbie, Emile Hirsch",
    "Plot": "A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.",
    "Language": "English, Italian, Spanish",
    "Country": "USA, UK, China",
    "Awards": "Won 3 Golden Globes. Another 70 wins & 242 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg",
    "imdbRating": 7.8,
    "imdbVotes": "318,841",
    "imdbID": "tt7131622",
    "Type": "movie", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x78z1km"
  },
  {
    "title": "Marriage Story",
    "Year": 2019,
    "Genre": "Comedy, Drama, Romance",
    "Actors": "Adam Driver, Scarlett Johansson, Julia Greer, Azhy Robertson",
    "Plot": "Noah Baumbach's incisive and compassionate look at a marriage breaking up and a family staying together.",
    "Language": "English",
    "Country": "UK, USA",
    "Awards": "Won 1 Golden Globe. Another 86 wins & 212 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BZGVmY2RjNDgtMTc3Yy00YmY0LTgwODItYzBjNWJhNTRlYjdkXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg",
    "imdbRating": 8.1,
    "imdbVotes": "108,524",
    "imdbID": "tt7653254",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x85f3uc"
  },
  {
    "title": "Little Women",
    "Year": 1994,
    "Genre": "Drama, Family, Romance",
    "Actors": "Winona Ryder, Gabriel Byrne, Trini Alvarado, Samantha Mathis",
    "Plot": "The March sisters live and grow in post-Civil War America.",
    "Language": "English, German, French",
    "Country": "USA, Canada",
    "Awards": "Nominated for 3 Oscars. Another 5 wins & 15 nominations.",
    "Poster": "https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/title-key-art/DP_4944434_LittleWomen_Cover_2000x3000_US.jpg?itok=HOMWAysI",
    "imdbRating": 7.3,
    "imdbVotes": "45,297",
    "imdbID": "tt0110367",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x8ic34b"
  },
  {
    "title": "Parasite",
    "Year": 2019,
    "Genre": "Comedy, Drama, Thriller",
    "Actors": "Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo, Woo-sik Choi",
    "Plot": "All unemployed, Ki-taek and his family take peculiar interest in the wealthy and glamorous Parks, as they ingratiate themselves into their lives and get entangled in an unexpected incident.",
    "Language": "Korean, English",
    "Country": "South Korea",
    "Awards": "Won 1 Golden Globe. Another 119 wins & 179 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    "imdbRating": 8.6,
    "imdbVotes": "128,604",
    "imdbID": "tt6751668",
    "Type": "movie", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8ny4p7"
  },
  {
    "title": "Knives Out",
    "Year": 2019,
    "Genre": "Comedy, Crime, Drama, Mystery, Thriller",
    "Actors": "Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis",
    "Plot": "A detective investigates the death of a patriarch of an eccentric, combative family.",
    "Language": "English, Spanish",
    "Country": "USA",
    "Awards": "Nominated for 3 Golden Globes. Another 22 wins & 37 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg",
    "imdbRating": 8.1,
    "imdbVotes": "66,522",
    "imdbID": "tt8946378",
    "Type": "movie",   
    "VideoLink":"https://www.dailymotion.com/embed/video/x80bv1q"
  },
  {
    "title": "Dolemite Is My Name",
    "Year": 2019,
    "Genre": "Biography, Comedy, Drama",
    "Actors": "Eddie Murphy, Keegan-Michael Key, Mike Epps, Craig Robinson",
    "Plot": "Eddie Murphy portrays real-life legend Rudy Ray Moore, a comedy and rap pioneer who proved naysayers wrong when his hilarious, obscene, kung-fu fighting alter ego, Dolemite, became a 1970s Blaxploitation phenomenon.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Nominated for 2 Golden Globes. Another 17 wins & 54 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMzFiYWQxYzgtOThmYi00ZmIwLWFlZWMtMzk2NTI2YTYzMjkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "imdbRating": 7.3,
    "imdbVotes": "31,613",
    "imdbID": "tt8526872",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x7fxqa3"
  },
  {
    "title": "Inception",
    "Year": 2010,
    "Genre": "Action, Adventure, Sci-Fi",
    "Actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
    "Plot": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    "Language": "English",
    "Country": "USA, UK",
    "Awards": "Won 4 Oscars. Another 152 wins & 220 nominations.",
    "Poster": "https://i.etsystatic.com/17257718/r/il/adc110/2428396175/il_570xN.2428396175_pra7.jpg",
    "imdbRating": 8.8,
    "imdbVotes": "2,314,604",
    "imdbID": "tt1375666",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x7s3d1r"
  },
  {
    "title": "The Shawshank Redemption",
    "Year": 1994,
    "Genre": "Drama",
    "Actors": "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    "Plot": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Nominated for 7 Oscars. Another 21 wins & 36 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "imdbRating": 9.3,
    "imdbVotes": "2,424,865",
    "imdbID": "tt0111161",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x8lygpt"
  },
  {
    "title": "The Dark Knight",
    "Year": 2008,
    "Genre": "Action, Crime, Drama",
    "Actors": "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    "Plot": "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    "Language": "English, Mandarin",
    "Country": "USA, UK",
    "Awards": "Won 2 Oscars. Another 157 wins & 163 nominations.",
    "Poster": "https://m.media-amazon.com/images/I/71rGQrF1flL._AC_UF1000,1000_QL80_.jpg",
    "imdbRating": 9.0,
    "imdbVotes": "2,404,199",
    "imdbID": "tt0468569",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x8oju3i"
  },
  {
    "title": "Pulp Fiction",
    "Year": 1994,
    "Genre": "Crime, Drama",
    "Actors": "John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis",
    "Plot": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    "Language": "English, Spanish, French",
    "Country": "USA",
    "Awards": "Won 1 Oscar. Another 69 wins & 75 nominations.",
    "Poster": "https://wallpapercave.com/wp/wp7665395.jpg",
    "imdbRating": 8.9,
    "imdbVotes": "1,914,076",
    "imdbID": "tt0110912",
    "Type": "movie",
    "VideoLink":"https://www.dailymotion.com/embed/video/x8ptonv"
  },
  {
    "title": "The Office",
    "Year": 2005,
    "Genre": "Comedy",
    "Actors": "Steve Carell, Rainn Wilson, John Krasinski, Jenna Fischer",
    "Plot": "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Won 5 Primetime Emmys. Another 45 wins & 185 nominations.",
    "Poster": "https://i.pinimg.com/736x/0e/15/bb/0e15bbb4a0c6914b4c8008b0d395bb28.jpg",
    "imdbRating": 8.9,
    "imdbVotes": "451,189",
    "imdbID": "tt0386676",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8gpk80"
  },
  {
    "title": "Fight Club",
    "Year": 1999,
    "Genre": "Drama",
    "Actors": "Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier",
    "Plot": "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
    "Language": "English",
    "Country": "USA, Germany",
    "Awards": "Nominated for 1 Oscar. Another 11 wins & 40 nominations.",
    "Poster": "https://m.media-amazon.com/images/I/71o1aRN1FJL.jpg",
    "imdbRating": 8.8,
    "imdbVotes": "2,009,021",
    "imdbID": "tt0137523",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x7mwtpv"
  },
  {
    "title": "The Mandalorian",
    "Year": 2019,
    "Genre": "Action, Adventure, Fantasy",
    "Actors": "Pedro Pascal, Gina Carano, Giancarlo Esposito, Rosario Dawson",
    "Plot": "A lone bounty hunter in the outer reaches of the galaxy far from the authority of the New Republic is hired to find and capture the Child.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Won 7 Primetime Emmys. Another 20 wins & 59 nominations.",
    "Poster": "https://w0.peakpx.com/wallpaper/835/353/HD-wallpaper-the-mandalorian-poster-the-mandalorian.jpg",
    "imdbRating": 8.8,
    "imdbVotes": "338,154",
    "imdbID": "tt8111088",
    "Type": "series",
    "VideoLink":"https://www.dailymotion.com/embed/video/x8hb7iq"
  },
  {
    "title": "Forrest Gump",
    "Year": 1994,
    "Genre": "Drama, Romance",
    "Actors": "Tom Hanks, Robin Wright, Gary Sinise, Sally Field",
    "Plot": "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Won 6 Oscars. Another 44 wins & 75 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    "imdbRating": 8.8,
    "imdbVotes": "1,958,379",
    "imdbID": "tt0109830",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x43a8nv"
  },
  {
    "title": "The Matrix",
    "Year": 1999,
    "Genre": "Action, Sci-Fi",
    "Actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
    "Plot": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    "Language": "English",
    "Country": "USA, Australia",
    "Awards": "Won 4 Oscars. Another 37 wins & 51 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    "imdbRating": 8.7,
    "imdbVotes": "1,714,392",
    "imdbID": "tt0133093",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x842cfo"
  },
  {
    "title": "The Godfather",
    "Year": 1972,
    "Genre": "Crime, Drama",
    "Actors": "Marlon Brando, Al Pacino, James Caan, Diane Keaton",
    "Plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "Language": "English, Italian, Latin",
    "Country": "USA",
    "Awards": "Won 3 Oscars. Another 27 wins & 30 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    "imdbRating": 9.1,
    "imdbVotes": "1,728,801",
    "imdbID": "tt0068646",
    "Type": "movie", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x6z5m1n"
  },
  {
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "Year": 2001,
    "Genre": "Action, Adventure, Drama",
    "Actors": "Elijah Wood, Ian McKellen, Orlando Bloom, Sean Bean",
    "Plot": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    "Language": "English, Sindarin",
    "Country": "New Zealand, USA",
    "Awards": "Won 4 Oscars. Another 115 wins & 124 nominations.",
    "Poster": "https://images-cdn.ubuy.co.in/634d1909d46781775673cd3d-lord-of-the-rings-fellowship-of-the-ring.jpg",
    "imdbRating": 8.8,
    "imdbVotes": "1,709,498",
    "imdbID": "tt0120737",
    "Type": "movie",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x16qy1o"
  },
  {
    "title": "The Witcher",
    "Year": 2019,
    "Genre": "Action, Adventure, Drama",
    "Actors": "Henry Cavill, Freya Allan, Anya Chalotra, Mimi Ndiweni",
    "Plot": "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    "Language": "English",
    "Country": "USA, Poland",
    "Awards": "Nominated for 1 Primetime Emmy. Another 3 wins & 13 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMDEwOWVlY2EtMWI0ZC00OWVmLWJmZGItYTk3YjYzN2Y0YmFkXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
    "imdbRating": 8.2,
    "imdbVotes": "398,624",
    "imdbID": "tt5180504",
    "Type": "series",
     
    "VideoLink":"https://www.dailymotion.com/embed/video/x8g2j5v"
  },
  {
    "title": "The Godfather: Part II",
    "Year": 1974,
    "Genre": "Crime, Drama",
    "Actors": "Al Pacino, Robert De Niro, Robert Duvall, Diane Keaton",
    "Plot": "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
    "Language": "English, Italian, Spanish, Latin, Sicilian",
    "Country": "USA",
    "Awards": "Won 6 Oscars. Another 11 wins & 20 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    "imdbRating": 9.0,
    "imdbVotes": "1,202,566",
    "imdbID": "tt0071562",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x84lrl5"
  },
  {
    "title": "The Lord of the Rings: The Return of the King",
    "Year": 2003,
    "Genre": "Action, Adventure, Drama",
    "Actors": "Elijah Wood, Viggo Mortensen, Ian McKellen, Orlando Bloom",
    "Plot": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    "Language": "English, Quenya, Old English, Sindarin",
    "Country": "New Zealand, USA",
    "Awards": "Won 11 Oscars. Another 197 wins & 122 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    "imdbRating": 8.9,
    "imdbVotes": "1,632,424",
    "imdbID": "tt0167260",
    "Type": "movie", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x7zdwz3"
  },
  {
    "title": "The Dark Knight Rises",
    "Year": 2012,
    "Genre": "Action, Adventure",
    "Actors": "Christian Bale, Tom Hardy, Anne Hathaway, Gary Oldman",
    "Plot": "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
    "Language": "English",
    "Country": "UK, USA",
    "Awards": "Nominated for 2 Oscars. Another 38 wins & 102 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg",
    "imdbRating": 8.4,
    "imdbVotes": "1,537,161",
    "imdbID": "tt1345836",
    "Type": "movie", 
    "VideoLink":"https://www.dailymotion.com/embed/video/xjze0z"
  },
  {
    "title": "The Lord of the Rings: The Two Towers",
    "Year": 2002,
    "Genre": "Action, Adventure, Drama",
    "Actors": "Elijah Wood, Ian McKellen, Viggo Mortensen, Orlando Bloom",
    "Plot": "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
    "Language": "English, Quenya, Old English, Sindarin",
    "Country": "New Zealand, USA",
    "Awards": "Won 2 Oscars. Another 62 wins & 125 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    "imdbRating": 8.7,
    "imdbVotes": "1,480,538",
    "imdbID": "tt0167261",
    "Type": "movie",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x7zdwz4"
  },
  {
    "title": "Breaking Bad",
    "Year": 2008,
    "Genre": "Crime, Drama, Thriller",
    "Actors": "Bryan Cranston, Aaron Paul, Anna Gunn, Betsy Brandt",
    "Plot": "A high school chemistry teacher turned methamphetamine manufacturer partners with a former student, leading to a dangerous and morally ambiguous world.",
    "Language": "English, Spanish",
    "Country": "USA",
    "Awards": "Won 16 Primetime Emmys. Another 151 wins & 225 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg",
    "imdbRating": 9.5,
    "imdbVotes": "1,527,456",
    "imdbID": "tt0903747",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x86esfl"
  },
  {
    "title": "Stranger Things",
    "Year": 2016,
    "Genre": "Drama, Fantasy, Horror",
    "Actors": "Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour",
    "Plot": "A group of kids in a small town uncover a series of supernatural mysteries and government conspiracies when a young girl with psychokinetic abilities appears.",
    "Language": "English, Russian",
    "Country": "USA",
    "Awards": "Won 8 Primetime Emmys. Another 71 wins & 188 nominations.",
    "Poster": "https://m.media-amazon.com/images/I/81L+tXLZYZL._AC_UF894,1000_QL80_.jpg",
    "imdbRating": 8.7,
    "imdbVotes": "897,710",
    "imdbID": "tt4574334",
    "Type": "series",
    "VideoLink":"https://www.dailymotion.com/embed/video/x5xgs2m"
  },

  {
    "title": "Friends",
    "Year": 1994,
    "Genre": "Comedy, Romance",
    "Actors": "Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc",
    "Plot": "Follows the personal and professional lives of six friends living in Manhattan.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Won 1 Golden Globe. Another 83 wins & 234 nominations.",
    "Poster": "https://i.pinimg.com/736x/2e/98/c5/2e98c58c758e3080a2cc84682cd66e4b.jpg",
    "imdbRating": 8.9,
    "imdbVotes": "893,015",
    "imdbID": "tt0108778",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8hsoha"
  },
  {
    "title": "The Simpsons",
    "Year": 1989,
    "Genre": "Animation, Comedy",
    "Actors": "Dan Castellaneta, Nancy Cartwright, Harry Shearer, Julie Kavner",
    "Plot": "The satiric adventures of a working-class family in the misfit city of Springfield.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Won 34 Primetime Emmys. Another 126 wins & 191 nominations.",
    "Poster": "https://i.pinimg.com/736x/c7/b4/b0/c7b4b0c0265a5bc34089e305f507492f.jpg",
    "imdbRating": 8.6,
    "imdbVotes": "375,443",
    "imdbID": "tt0096697",
    "Type": "series", 
    "VideoLink":"https://www.dailymotion.com/embed/video/x8a7ls2"
  },

  {
    "title": "Narcos",
    "Year": 2015,
    "Genre": "Biography, Crime, Drama",
    "Actors": "Pedro Pascal, Wagner Moura, Boyd Holbrook, Alberto Ammann",
    "Plot": "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.",
    "Language": "English, Spanish",
    "Country": "USA, Mexico",
    "Awards": "Nominated for 2 Golden Globes. Another 7 wins & 19 nominations.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNmFjODU3YzgtMGUwNC00ZGI3LWFkZjQtMjkxZDc3NmQ1MzcyXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
    "imdbRating": 8.8,
    "imdbVotes": "372,088",
    "imdbID": "tt2707408",
    "Type": "series",  
    "VideoLink":"https://www.dailymotion.com/embed/video/x3257kr"
  },
]


module.exports =  array;